spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:43306/subway?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: masterpw

  jpa:
    hibernate:
      ddl-auto: none
